name: Validate Packer Script

on:
  pull_request:
    branches:
      - main

jobs:
  validate_packer:
    name: Validate Packer Script
    runs-on: ubuntu-latest
    if: github.repository_owner == 'CSYE6225-NetworkStructures'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build Application with pkg
        run: |
          npm install
          pkg server.js --output infra/packer/dist/webapp --targets node18-linux-x64
          chmod +x infra/packer/dist/webapp
          echo "Binary created at infra/packer/dist/webapp"

      - name: Install Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: latest

      - name: Initialize Packer
        working-directory: infra/packer
        run: packer init .

      - name: Check Packer Formatting
        working-directory: infra/packer
        run: |
          if packer fmt -check -diff .; then
            echo "Packer format is correct."
          else
            echo "Packer format check failed. Run 'packer fmt' locally to fix formatting."
            exit 1
          fi

      - name: Validate Packer Configuration
        working-directory: infra/packer
        run: packer validate machine-image.pkr.hcl
